ApplicationWeb/Models/ElevesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ApplicationWeb.Models
{
    public class ElevesViewModel
    {
        public int id { get; set; }
        public int classeId { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public DateTime dateNaissance { get; set; }
        public List<NoteViewModel> notes { get; set; }
        public List<AbsenceViewModel> absences { get; set; }
        public double moyenne { get; set; }
    }
}

ApplicationWeb/Controllers/ClasseController.cs
using ApplicationWeb.Models;
using BusinessLayer;
using ModelDeDonnees.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationWeb.Controllers
{
    public class ClasseController : Controller
    {

        private BusinessManager _bm;
        public ClasseController()
        {
            _bm = BusinessManager.GetInstance();
        }

        public ActionResult DetailClasse(int id)
        {
            Classe classe = _bm.GetClasseById(id);

            List<Eleve> eleves = _bm.GetElevesByClasseId(classe.Id);
            List<ElevesViewModel> elevesViewModels = new List<ElevesViewModel>();
            foreach (var eleve in eleves)
            {
                elevesViewModels.Add(new ElevesViewModel
                {
                    id = eleve.Id,
                    nom = eleve.nom,
                    prenom = eleve.prenom,
                    dateNaissance = eleve.dateNaissance
                });
            }

            ClasseViewModel classeViewModel = new ClasseViewModel
            {
                id = classe.Id,
                Niveau = classe.Niveau,
                NomEtablissement = classe.NomEtablissement,
                eleves = elevesViewModels
            };

            return View(classeViewModel ?? null);
        }

        public ActionResult DeleteClasse(int id)
        {

            return Content("todo");
        }

        public ActionResult ActionClasse(int id)
        {
            Classe classe = _bm.GetClasseById(id);

            ElevesViewModel elevesViewModel = new ElevesViewModel
            {
                classeId = classe.Id,
                dateNaissance = DateTime.Now
            };

            return View(elevesViewModel);
        }

        public ActionResult updateClasse()
        {


            string nom = Request.Params["nom"];
            string niveau = Request.Params["niveau"];
            int classeId = int.Parse(Request.Params["idClasse"]);

            Classe classe = _bm.GetClasseById(classeId);

            string retour;
            try
            {
                _bm.UpdateClasseById(classe.Id, nom, niveau);
                retour = "ok";
            }
            catch (Exception e)
            {
                retour = e.Message;
            }

            return Content(retour);
        }
    }
}

ApplicationWeb/Controllers/ElevesController.cs
using ApplicationWeb.Models;
using BusinessLayer;
using ModelDeDonnees.Entities;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Web.Mvc;

namespace ApplicationWeb.Controllers
{
    public class ElevesController : Controller
    {
        private BusinessManager _bm;
        public ElevesController()
        {
            _bm = BusinessManager.GetInstance();
        }

        public ActionResult DetailELeve(int id)
        {
            Eleve eleve = _bm.GetEleveById(id);

            List<Notes> notes = _bm.GetNotesByEleveId(eleve.Id);
            List<NoteViewModel> noteViewModels = new List<NoteViewModel>();
            foreach (var note in notes)
            {
                noteViewModels.Add(new NoteViewModel
                {
                    Id = note.Id,
                    Appreciation = note.Appreciation,
                    DateNote = note.DateNote,
                    Matiere = note.Matiere,
                    Note = note.Note
                });
            }

            List<Absence> absences = _bm.GetAbscenceByEleveId(eleve.Id);
            List<AbsenceViewModel> absenceViewModels = new List<AbsenceViewModel>();
            foreach (var absence in absences)
            {
                absenceViewModels.Add(new AbsenceViewModel
                {
                    Id = absence.Id,
                    DateAbsence = absence.DateAbsence,
                    Motif = absence.Motif
                });
            }

            ElevesViewModel elevesViewModel = new ElevesViewModel
            {
                id = eleve.Id,
                nom = eleve.nom,
                prenom = eleve.prenom,
                dateNaissance = eleve.dateNaissance,
                classeId = _bm.GetClasseById(eleve.classeId).Id,
                notes = noteViewModels,
                absences = absenceViewModels,
                moyenne = _bm.GetAverageByEleveId(eleve.Id)
            };

            return View(elevesViewModel);
        }
        
        public ActionResult DeleteNote(int id)
        {
            string reponse;
            try
            {
                _bm.DeleteNoteById(id);
                reponse = "ok";
            }
            catch (Exception e)
            {
                reponse = e.Message;
            }

            return Content(reponse);
        }
        
        public ActionResult DeleteAbsence(int id)
        {
            string reponse;
            try
            {
                _bm.DeleteAbscenceById(id);
                reponse = "ok";
            }
            catch (Exception e)
            {
                reponse = e.Message;
            }

            return Content(reponse);
        }
        
        public ActionResult ActionNote(int id, int idEleve)
        {
            NoteViewModel noteViewModel;

            if (id == -1) 
            {
                noteViewModel = new NoteViewModel { EleveId = idEleve, DateNote = DateTime.Now };
            }
            else
            {
                Notes note = _bm.GetNoteById(id);

                noteViewModel = new NoteViewModel
                {
                    Id = note.Id,
                    Appreciation = note.Appreciation,
                    DateNote = note.DateNote,
                    Matiere = note.Matiere,
                    Note = note.Note,
                    EleveId = note.EleveId
                };
            }
          
            return View(noteViewModel);
        }
        
        public ActionResult createUpdateNote(int id)
        {
            string retour;

            Notes note = _bm.GetNoteById(id);

            string pattern = "dd/MM/yyyy";
            DateTime parsedDate;
            DateTime dateNote;

            String date = Request.Params["dateNote"];
            int idEleve = int.Parse(Request.Params["idEleve"]);
            string matiere = Request.Params["matiere"];
            int noteVal = int.Parse(Request.Params["note"]);
            string appreciation = Request.Params["appreciation"];

            if (DateTime.TryParseExact(date, pattern, null, DateTimeStyles.None, out parsedDate))
            {
                dateNote = parsedDate;
            }
            else
            {
                dateNote = DateTime.Now;
            }

            if (note == null)
            {
                try
                {
                    _bm.CreateNote(matiere, dateNote, appreciation, noteVal, idEleve);
                }
                catch(Exception e)
                {
                    retour = e.Message;
                }
                retour = "ok";
            }
            else
            {
                try
                {
                    _bm.UpdateNoteById(note.Id, matiere, dateNote, appreciation, noteVal, idEleve);
                }
                catch (Exception e)
                {
                    retour = e.Message;
                }
                retour = "ok";
            }
            
            return Content(retour) ;
        }
        
        public ActionResult createUpdateAbsence(int id)
        {
            string retour;

            Absence absence = _bm.GetAbscenceById(id);

            string pattern = "dd/MM/yyyy";
            DateTime parsedDate;
            DateTime dateNote;

            String date = Request.Params["date"];
            int idEleve = int.Parse(Request.Params["idEleve"]);
            string motif = Request.Params["motif"];

            if(DateTime.TryParseExact(date, pattern, null, DateTimeStyles.None, out parsedDate))
            {
                dateNote = parsedDate;
            }
            else
            {
                dateNote = DateTime.Now;
            }
            
            if (absence == null)
            {
                try
                {
                    _bm.CreateAbscence(dateNote,motif,idEleve);
                }
                catch(Exception e)
                {
                    retour = e.Message;
                }
                retour = "ok";
            }
            else
            {
                try
                {
                    _bm.UpdateAbscenceById(absence.Id, dateNote, motif, idEleve);
                }
                catch (Exception e)
                {
                    retour = e.Message;
                }
                retour = "ok";
            }
            
            return Content(retour) ;
        }
        
        public ActionResult ActionAbsence(int id, int idEleve)
        {
            AbsenceViewModel absenceViewModel;

            if (id == -1)
            {
                absenceViewModel = new AbsenceViewModel { EleveId = idEleve, DateAbsence = DateTime.Now };
            }
            else
            {
                Absence absence = _bm.GetAbscenceById(id);
                absenceViewModel = new AbsenceViewModel
                {
                    Id = absence.Id,
                    DateAbsence = absence.DateAbsence,
                    Motif = absence.Motif,
                    EleveId = absence.EleveId
                };
            }

            return View(absenceViewModel);
        }

        public ActionResult createEleve()
        {

            string pattern = "dd/MM/yyyy";
            DateTime parsedDate;
            DateTime dateNaissance;

            String date = Request.Params["dateNaissance"];
            string nom = Request.Params["nom"];
            string prenom = Request.Params["prenom"];
            int classeId = int.Parse(Request.Params["classeId"]);

            if (DateTime.TryParseExact(date, pattern, null, DateTimeStyles.None, out parsedDate))
            {
                dateNaissance = parsedDate;
            }
            else
            {
                dateNaissance = DateTime.Now;
            }

            string retour;
            try
            {
                _bm.CreateEleve(nom,prenom,dateNaissance,classeId);
                retour = "ok";
            }
            catch (Exception e)
            {
                retour = e.Message;
            }
           
            return Content(retour);
        }
        
        public ActionResult updateEleve()
        {

            string pattern = "dd/MM/yyyy";
            DateTime parsedDate;
            DateTime dateNaissance;

            String date = Request.Params["dateNaissance"];
            string nom = Request.Params["nom"];
            string prenom = Request.Params["prenom"];
            int idEleve = int.Parse(Request.Params["idEleve"]);
            int classeId = int.Parse(Request.Params["classeId"]);

            if (DateTime.TryParseExact(date, pattern, null, DateTimeStyles.None, out parsedDate))
            {
                dateNaissance = parsedDate;
            }
            else
            {
                dateNaissance = DateTime.Now;
            }

            Eleve eleve = _bm.GetEleveById(idEleve);

            string retour;
            try
            {
                _bm.UpdateEleveById(eleve.Id,nom,prenom,dateNaissance,classeId);
                retour = "ok";
            }
            catch (Exception e)
            {
                retour = e.Message;
            }
           
            return Content(retour);
        }
    }
}

ApplicationWeb/Views/Eleves/ActionAbsence.cshtml
@using ApplicationWeb.Models
@model  AbsenceViewModel

@if (Model.Motif != null)
{
    <h2>Modifier une absence</h2>
}
else
{
    <h2>Ajouter une absence</h2>
}

<div>
    <div>
        <div>
            <div>
                <form>
                    <div class="form-row">
                        <label for="motifAbscence">Motif:</label>
                        <input type="text" class="form-control" id="motifAbscence" value="@Model.Motif" style="max-width: 100%">
                    </div>
                    <div class="form-group">
                        <label for="dateAbscence">Date:</label>
                        <input type="text" class="form-control" id="dateAbscence" value="@Model.DateAbsence.Date.ToString("dd/MM/yyyy")" style="max-width: 100%">
                    </div>
                </form>
            </div>
            <div>
                <a class="btn btn-danger" onclick="history.go(-1)">Annuler</a>
                <a class="btn btn-primary" onclick="valider()">valider</a>
            </div>
        </div>
    </div>
</div>

<script>
    function valider() {
        $.ajax({
            url: "@Url.Action("createUpdateAbsence", new { id = Model.Id })",
            method: "POST",
            data: {
                idEleve: @Model.EleveId,
                motif: $('#motifAbscence').val(),
                date: $('#dateAbscence').val()
            },
            success: function (data) {
                if (data == "ok") {
                    document.location.href = "@Url.Action("DetailEleve", new { id = Model.EleveId })"
                } else {
                    alert(data);
                }
            }
        });
    }
</script>

ApplicationWeb/Views/Eleves/ActionNote.cshtml
@using ApplicationWeb.Models
@model  NoteViewModel

@if (Model.Matiere != null)
{
    <h2>Modifier une note</h2>
}
else
{
    <h2>Ajouter une note</h2>
}

<div>
    <div>
        <div>
            <div>
                <form>
                    <div class="form-row">
                        <label for="matiereNote">Matière:</label>
                        <input type="text" class="form-control" id="matiereNote" value="@Model.Matiere" style="max-width: 100%">
                    </div>
                    <div class="form-group">
                        <label for="dateNote">Note:</label>
                        <input type="text" class="form-control" id="valeurNote" value="@Model.Note" style="max-width: 100%">
                    </div>
                    <div class="form-group">
                        <label for="valeurNote">Date:</label>
                        <input type="text" class="form-control" id="dateNote" value="@Model.DateNote.Date.ToString("dd/MM/yyyy")" style="max-width: 100%">
                    </div>
                    <div class="form-group">
                        <label for="noteAppreciation">Appreciation:</label>
                        <input type="text" class="form-control" id="noteAppreciation" value="@Model.Appreciation" style="max-width: 100%">
                    </div>
                </form>
            </div>
            <div>
                <a class="btn btn-danger" onclick="history.go(-1)">Annuler</a>
                <a class="btn btn-primary" onclick="valider()">valider</a>
            </div>
        </div>
    </div>
</div>

<script>
    function valider() {
        $.ajax({
            url: "@Url.Action("createUpdateNote", new { id = Model.Id })",
            method: "POST",
            data: {
                idEleve: @Model.EleveId,
                matiere: $('#matiereNote').val(),
                note: $('#valeurNote').val(),
                dateNote: $('#dateNote').val(),
                appreciation: $('#noteAppreciation').val()
            },
            success: function (data) {
                if (data == "ok") {
                    document.location.href = "@Url.Action("DetailEleve", new { id = Model.EleveId })"
                } else {
                    alert(data);
                }
            }
        });
    }
</script>

ApplicationWeb/Views/Eleves/DetailELeve.cshtml
@using ApplicationWeb.Models
@model  ElevesViewModel

    <div class="container">
        <br />
        <div class="row">
            <form>
                <div class="form-row">
                    <label for="EleveNom">Nom:</label>
                    <input type="text" class="form-control" id="EleveNom" value="@Model.nom" style="max-width: 100%">
                </div>
                <div class="form-group">
                    <label for="ElevePrenom">Prénom:</label>
                    <input type="text" class="form-control" id="ElevePrenom" value="@Model.prenom" style="max-width: 100%">
                </div>
                <div class="form-group">
                    <label for="EleveDate">Date de naissance:</label>
                    <input type="text" class="form-control" id="EleveDate" value="@Model.dateNaissance.Date.ToString("dd/MM/yyyy")" style="max-width: 100%">
                </div>
                <div class="form-group">
                    <label for="EleveClasse">Classe:</label>
                    <input id="EleveClasse" class="form-control" type="text" placeholder="@Model.classeId" readonly style="max-width: 100%">
                </div>
                <a class="btn btn-success" onclick="modifierEleve()">Modifier</a>
                <a class="btn btn-danger" onclick="history.go(-1)">Annuler</a>
                @Html.ActionLink("Voir la classe", "DetailClasse", "Classe", new { id = Model.classeId }, new { @class = "btn btn-primary" })
            </form>
        </div>

        <h1>Notes</h1>
        <h4>@Model.moyenne.ToString("00.00")/20</h4>
        <br />
        @if (Model.notes.Count > 0)
        {
            <figure id="chart" class="container"></figure>
            <figure id="chart2" class="container"></figure>
        }
        <br />
        <div class="row">
            <table class="table table-striped table-hover table-sm table-responsive tableauDetailEleves">
                <thead>
                    <tr>
                        <th>Matière</th>
                        <th>Date</th>
                        <td>Note</td>
                        <th>Appreciation</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var note in Model.notes)
                    {
                        <tr>
                            <td>@note.Matiere</td>
                            <td>@note.DateNote.Date.ToString("dd/MM/yyyy")</td>
                            <td>@note.Note</td>
                            <td>@note.Appreciation</td>
                            <td>
                                <a class="btn btn-danger" onclick="supprimerNote(@note.Id)">Supprimer</a>
                                <a class="btn btn-primary" href="@Url.Action("ActionNote", new { id = note.Id, idEleve = note.EleveId })">Modifier</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <a class="btn btn-success" href="@Url.Action("ActionNote", new { id = -1, idEleve = Model.id })">Ajouter</a>
        </div>
        <h1>Absences</h1>
        <h4>@Model.absences.Count absences</h4>

        <br />
        <div class="row">
            <table class="table table-striped table-hover table-sm table-responsive tableauDetailEleves">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Motif</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var absence in Model.absences)
                    {
                        <tr>
                            <td>@absence.DateAbsence.Date.ToString("dd/MM/yyyy")</td>
                            <td>@absence.Motif</td>
                            <td>
                                <a class="btn btn-danger" onclick="supprimerAbsence(@absence.Id)">Supprimer</a>
                                <a class="btn btn-primary" href="@Url.Action("ActionAbsence", new { id = absence.Id, idEleve = absence.EleveId })">Modifier</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <a class="btn btn-success" href="@Url.Action("ActionAbsence", new { id = -1, idEleve = Model.id })">Ajouter</a>
        </div>
    </div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
    function chart() {
        // Charger l'API de visualisation et le paquet corechart.
        google.charts.load('current', { 'packages': ['corechart'] });

        // Définit un rappel à exécuter lorsque l'API Google Visualization est chargée.
        google.charts.setOnLoadCallback(drawChart);

        /* Callback qui crée et remplit une table de données,
        instancie le graphique en secteurs,
        transmet les données et le dessine. */
        function drawChart() {
            // Crée la table de données.
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Topping');
            data.addColumn('number', 'Slices');

            const arr = JSON.parse('@Html.Raw(Json.Encode(@Model.notes))')
            const arr2 = new Array();

            var occurrences = {};
            for (var i = 0, j = arr.length; i < j; i++) {
                occurrences[arr[i]['Matiere']] = (occurrences[arr[i]['Matiere']] || 0) + 1;
            }

            for (i = 0; i < arr.length; i++) {
                if (!arr2.includes(arr[i]['Matiere'])) {

                    arr2.push(arr[i]['Matiere'])
                    data.addRows([[arr[i]['Matiere'], occurrences[arr[i]['Matiere']]]])
                }
            }

            // Définir les options du graphique
            var options = {
                'colors': ['#e0440e', '#e6693e', '#ec8f6e', '#f3b49f', '#f6c7b6'],
                is3D: false,
                'width': 600,
                'height': 300
            };


            // Instancie et dessine notre graphique en passant certaines options.
            var chart = new google.visualization.PieChart(document.getElementById('chart'));
            chart.draw(data, options);

        }
    }
    chart();

</script>
<script>
    function supprimerNote(id) {
        $.ajax({
            url: "/Eleves/DeleteNote/"+id ,
            method: "POST",
            data: {
                idNote: id,
            },
            success: function (data) {
                if (data == "ok") {
                    document.location.reload();
                } else {
                    alert(data);
                }
            }
        });
    }
    function supprimerAbsence(id) {
        $.ajax({
            url: "/Eleves/DeleteAbsence/"+id ,
            method: "POST",
            data: {
                idNote: id,
            },
            success: function (data) {
                if (data == "ok") {
                    document.location.reload();
                } else {
                    alert(data);
                }
            }
        });
    }

    function modifierEleve() {
        $.ajax({
            url: "@Url.Action("updateEleve", new { id = Model.id })" ,
            method: "POST",
            data: {
                idEleve: @Model.id,
                nom: $('#EleveNom').val(),
                prenom: $('#ElevePrenom').val(),
                dateNaissance: $('#EleveDate').val(),
                classeId: @Model.classeId
            },
            success: function (data) {
                if (data == "ok") {
                    document.location.reload();
                } else {
                    alert(data);
                }
            }
        });
    }
</script>