ApplicationWeb/Models/ClasseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ApplicationWeb.Models
{
    public class ClasseViewModel
    {
        public int id { get; set; }
        public string NomEtablissement { get; set; }
        public string Niveau { get; set; }
        public List<ElevesViewModel> eleves { get; set; }
    }
}

ApplicationWeb/Controllers/ClasseController.cs
using ApplicationWeb.Models;
using BusinessLayer;
using ModelDeDonnees.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationWeb.Controllers
{
    public class ClasseController : Controller
    {

        private BusinessManager _bm;
        public ClasseController()
        {
            _bm = BusinessManager.GetInstance();
        }

        public ActionResult DetailClasse(int id)
        {
            Classe classe = _bm.GetClasseById(id);

            List<Eleve> eleves = _bm.GetElevesByClasseId(classe.Id);
            List<ElevesViewModel> elevesViewModels = new List<ElevesViewModel>();
            foreach (var eleve in eleves)
            {
                elevesViewModels.Add(new ElevesViewModel
                {
                    id = eleve.Id,
                    nom = eleve.nom,
                    prenom = eleve.prenom,
                    dateNaissance = eleve.dateNaissance
                });
            }

            ClasseViewModel classeViewModel = new ClasseViewModel
            {
                id = classe.Id,
                Niveau = classe.Niveau,
                NomEtablissement = classe.NomEtablissement,
                eleves = elevesViewModels
            };

            return View(classeViewModel ?? null);
        }

        public ActionResult DeleteClasse(int id)
        {

            return Content("todo");
        }

        public ActionResult ActionClasse(int id)
        {
            Classe classe = _bm.GetClasseById(id);

            ElevesViewModel elevesViewModel = new ElevesViewModel
            {
                classeId = classe.Id,
                dateNaissance = DateTime.Now
            };

            return View(elevesViewModel);
        }

        public ActionResult updateClasse()
        {


            string nom = Request.Params["nom"];
            string niveau = Request.Params["niveau"];
            int classeId = int.Parse(Request.Params["idClasse"]);

            Classe classe = _bm.GetClasseById(classeId);

            string retour;
            try
            {
                _bm.UpdateClasseById(classe.Id, nom, niveau);
                retour = "ok";
            }
            catch (Exception e)
            {
                retour = e.Message;
            }

            return Content(retour);
        }
    }
}

ApplicationWeb/Controllers/ElevesController.cs
using ApplicationWeb.Models;
using BusinessLayer;
using ModelDeDonnees.Entities;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Web.Mvc;

namespace ApplicationWeb.Controllers
{
    public class ElevesController : Controller
    {
        private BusinessManager _bm;
        public ElevesController()
        {
            _bm = BusinessManager.GetInstance();
        }

        public ActionResult DetailELeve(int id)
        {
            Eleve eleve = _bm.GetEleveById(id);

            List<Notes> notes = _bm.GetNotesByEleveId(eleve.Id);
            List<NoteViewModel> noteViewModels = new List<NoteViewModel>();
            foreach (var note in notes)
            {
                noteViewModels.Add(new NoteViewModel
                {
                    Id = note.Id,
                    Appreciation = note.Appreciation,
                    DateNote = note.DateNote,
                    Matiere = note.Matiere,
                    Note = note.Note
                });
            }

            List<Absence> absences = _bm.GetAbscenceByEleveId(eleve.Id);
            List<AbsenceViewModel> absenceViewModels = new List<AbsenceViewModel>();
            foreach (var absence in absences)
            {
                absenceViewModels.Add(new AbsenceViewModel
                {
                    Id = absence.Id,
                    DateAbsence = absence.DateAbsence,
                    Motif = absence.Motif
                });
            }

            ElevesViewModel elevesViewModel = new ElevesViewModel
            {
                id = eleve.Id,
                nom = eleve.nom,
                prenom = eleve.prenom,
                dateNaissance = eleve.dateNaissance,
                classeId = _bm.GetClasseById(eleve.classeId).Id,
                notes = noteViewModels,
                absences = absenceViewModels,
                moyenne = _bm.GetAverageByEleveId(eleve.Id)
            };

            return View(elevesViewModel);
        }
        
        public ActionResult DeleteNote(int id)
        {
            string reponse;
            try
            {
                _bm.DeleteNoteById(id);
                reponse = "ok";
            }
            catch (Exception e)
            {
                reponse = e.Message;
            }

            return Content(reponse);
        }
        
        public ActionResult DeleteAbsence(int id)
        {
            string reponse;
            try
            {
                _bm.DeleteAbscenceById(id);
                reponse = "ok";
            }
            catch (Exception e)
            {
                reponse = e.Message;
            }

            return Content(reponse);
        }
        
        public ActionResult ActionNote(int id, int idEleve)
        {
            NoteViewModel noteViewModel;

            if (id == -1) 
            {
                noteViewModel = new NoteViewModel { EleveId = idEleve, DateNote = DateTime.Now };
            }
            else
            {
                Notes note = _bm.GetNoteById(id);

                noteViewModel = new NoteViewModel
                {
                    Id = note.Id,
                    Appreciation = note.Appreciation,
                    DateNote = note.DateNote,
                    Matiere = note.Matiere,
                    Note = note.Note,
                    EleveId = note.EleveId
                };
            }
          
            return View(noteViewModel);
        }
        
        public ActionResult createUpdateNote(int id)
        {
            string retour;

            Notes note = _bm.GetNoteById(id);

            string pattern = "dd/MM/yyyy";
            DateTime parsedDate;
            DateTime dateNote;

            String date = Request.Params["dateNote"];
            int idEleve = int.Parse(Request.Params["idEleve"]);
            string matiere = Request.Params["matiere"];
            int noteVal = int.Parse(Request.Params["note"]);
            string appreciation = Request.Params["appreciation"];

            if (DateTime.TryParseExact(date, pattern, null, DateTimeStyles.None, out parsedDate))
            {
                dateNote = parsedDate;
            }
            else
            {
                dateNote = DateTime.Now;
            }

            if (note == null)
            {
                try
                {
                    _bm.CreateNote(matiere, dateNote, appreciation, noteVal, idEleve);
                }
                catch(Exception e)
                {
                    retour = e.Message;
                }
                retour = "ok";
            }
            else
            {
                try
                {
                    _bm.UpdateNoteById(note.Id, matiere, dateNote, appreciation, noteVal, idEleve);
                }
                catch (Exception e)
                {
                    retour = e.Message;
                }
                retour = "ok";
            }
            
            return Content(retour) ;
        }
        
        public ActionResult createUpdateAbsence(int id)
        {
            string retour;

            Absence absence = _bm.GetAbscenceById(id);

            string pattern = "dd/MM/yyyy";
            DateTime parsedDate;
            DateTime dateNote;

            String date = Request.Params["date"];
            int idEleve = int.Parse(Request.Params["idEleve"]);
            string motif = Request.Params["motif"];

            if(DateTime.TryParseExact(date, pattern, null, DateTimeStyles.None, out parsedDate))
            {
                dateNote = parsedDate;
            }
            else
            {
                dateNote = DateTime.Now;
            }
            
            if (absence == null)
            {
                try
                {
                    _bm.CreateAbscence(dateNote,motif,idEleve);
                }
                catch(Exception e)
                {
                    retour = e.Message;
                }
                retour = "ok";
            }
            else
            {
                try
                {
                    _bm.UpdateAbscenceById(absence.Id, dateNote, motif, idEleve);
                }
                catch (Exception e)
                {
                    retour = e.Message;
                }
                retour = "ok";
            }
            
            return Content(retour) ;
        }
        
        public ActionResult ActionAbsence(int id, int idEleve)
        {
            AbsenceViewModel absenceViewModel;

            if (id == -1)
            {
                absenceViewModel = new AbsenceViewModel { EleveId = idEleve, DateAbsence = DateTime.Now };
            }
            else
            {
                Absence absence = _bm.GetAbscenceById(id);
                absenceViewModel = new AbsenceViewModel
                {
                    Id = absence.Id,
                    DateAbsence = absence.DateAbsence,
                    Motif = absence.Motif,
                    EleveId = absence.EleveId
                };
            }

            return View(absenceViewModel);
        }

        public ActionResult createEleve()
        {

            string pattern = "dd/MM/yyyy";
            DateTime parsedDate;
            DateTime dateNaissance;

            String date = Request.Params["dateNaissance"];
            string nom = Request.Params["nom"];
            string prenom = Request.Params["prenom"];
            int classeId = int.Parse(Request.Params["classeId"]);

            if (DateTime.TryParseExact(date, pattern, null, DateTimeStyles.None, out parsedDate))
            {
                dateNaissance = parsedDate;
            }
            else
            {
                dateNaissance = DateTime.Now;
            }

            string retour;
            try
            {
                _bm.CreateEleve(nom,prenom,dateNaissance,classeId);
                retour = "ok";
            }
            catch (Exception e)
            {
                retour = e.Message;
            }
           
            return Content(retour);
        }
        
        public ActionResult updateEleve()
        {

            string pattern = "dd/MM/yyyy";
            DateTime parsedDate;
            DateTime dateNaissance;

            String date = Request.Params["dateNaissance"];
            string nom = Request.Params["nom"];
            string prenom = Request.Params["prenom"];
            int idEleve = int.Parse(Request.Params["idEleve"]);
            int classeId = int.Parse(Request.Params["classeId"]);

            if (DateTime.TryParseExact(date, pattern, null, DateTimeStyles.None, out parsedDate))
            {
                dateNaissance = parsedDate;
            }
            else
            {
                dateNaissance = DateTime.Now;
            }

            Eleve eleve = _bm.GetEleveById(idEleve);

            string retour;
            try
            {
                _bm.UpdateEleveById(eleve.Id,nom,prenom,dateNaissance,classeId);
                retour = "ok";
            }
            catch (Exception e)
            {
                retour = e.Message;
            }
           
            return Content(retour);
        }
    }
}

ApplicationWeb/Views/Classe/ActionClasse.cshtml
@using ApplicationWeb.Models
@model  ElevesViewModel

<h2>Ajouter un élève</h2>

<div>
    <div>
        <div>
            <div>
                <form>
                    <div class="form-row">
                        <label for="nom">Nom:</label>
                        <input type="text" class="form-control" id="nom" value="@Model.nom" style="max-width: 100%">
                    </div>
                    <div class="form-row">
                        <label for="prenom">Prénom:</label>
                        <input type="text" class="form-control" id="prenom" value="@Model.prenom" style="max-width: 100%">
                    </div>
                    <div class="form-group">
                        <label for="dateNaissance">date de naissance:</label>
                        <input type="text" class="form-control" id="dateNaissance" value="@Model.dateNaissance.Date.ToString("dd/MM/yyyy")" style="max-width: 100%">
                    </div>
                </form>
            </div>
            <div>
                <a class="btn btn-danger" onclick="history.go(-1)">Annuler</a>
                <a class="btn btn-primary" onclick="valider()">valider</a>
            </div>
        </div>
    </div>
</div>
@*@Url.Action("createEleve")*@
<script>
    function valider() {
        $.ajax({
            url: "/Eleves/create",
            method: "POST",
            data: {
                classeId: "@Model.classeId",
                nom: $('#nom').val(),
                prenom: $('#prenom').val(),
                dateNaissance: $('#dateNaissance').val()
            },
            success: function (data) {
                if (data == "ok") {
                    document.location.href = "@Url.Action("DetailClasse", new { id = Model.classeId })"
                } else {
                    alert(data);
                }
            }
        });
    }
</script>

ApplicationWeb/Views/Classe/DetailClasse.cshtml
@using ApplicationWeb.Models
@model  ClasseViewModel

<div class="container">
    <br />
    <div class="row">
        <form>
            <div class="form-row">
                <label for="NomEtablissement">Nom établissement:</label>
                <input type="text" class="form-control" id="NomEtablissement" value="@Model.NomEtablissement" style="max-width: 100%">
            </div>
            <div class="form-group">
                <label for="Niveau">Niveau:</label>
                <input type="text" class="form-control" id="Niveau" value="@Model.Niveau" style="max-width: 100%">
            </div>
            <a class="btn btn-success" onclick="modifierClasse()">Modifier</a>
            <a class="btn btn-danger" onclick="history.go(-1)">Annuler</a>
        </form>
    </div>
    <h1>Elèves</h1>
    <br />
    <div class="row">
        <table class="table table-striped table-hover table-sm table-responsive tableauDetailEleves">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Date de naissance</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var eleve in Model.eleves)
                {
                <tr>
                    <td>@eleve.nom</td>
                    <td>@eleve.prenom</td>
                    <td>@eleve.dateNaissance.Date.ToString("dd/MM/yyyy")</td>
                    <td>
                        @Html.ActionLink("Modifier", "DetailELeve", "Eleves", new { id = eleve.id }, new { @class = "btn btn-primary" })
                    </td>
                </tr>
                }
            </tbody>
        </table>
        <a class="btn btn-success" href="@Url.Action("ActionClasse", new { id = Model.id })">Ajouter</a>
    </div>
</div>

<script>
    function modifierClasse() {
        $.ajax({
            url: "@Url.Action("updateClasse", new { id = Model.id })" ,
            method: "POST",
            data: {
                idClasse: @Model.id,
                nom: $('#NomEtablissement').val(),
                niveau: $('#Niveau').val()
            },
            success: function (data) {
                if (data == "ok") {
                    document.location.reload();
                } else {
                    alert(data);
                }
            }
        });
    }
</script>